$env:AZURE_SUBSCRIPTION_ID = "e0f91dc0-102c-41ae-a3b3-d256a2ee118d"
$env:TARGET_RESOURCE_GROUP_NAME = "jericos-stuff-rg"
$env:CONTAINER_GROUP_NAME = "hello-world-cg"
$env:TARGET_SUBNET_RESOURCE_ID = "/subscriptions/e0f91dc0-102c-41ae-a3b3-d256a2ee118d/resourceGroups/jericos-stuff-rg/providers/Microsoft.Network/virtualNetworks/jericos-vnet-uaen/subnets/aci-cg-subnet"
$env:TARGET_SUBNET_NAME ="aci-cg-subnet"
$env:TEMPLATE_FILE_NAME = "container-group-with-az-dns-vnet.json"